<x-admin.shell title="Reports" heading="" subheading="">

    <!-- Print-ONLY Header -->
    <div class="print-report-header" style="display: none;">
        <div class="print-header-top">
            <div>
                <h1 class="print-title">kape-nated &middot; Executive Report</h1>
                <p class="print-sub">Café Performance, Sales & Stock Analytics</p>
            </div>
            <div class="print-meta-box">
                <p><strong>Export Date:</strong> {{ \Illuminate\Support\Carbon::now()->format('d M Y, h:i A') }}</p>
                <p><strong>Report Range:</strong> <span id="printReportRangeText">{{ \Illuminate\Support\Carbon::today()->format('d M Y') }}</span></p>
                <p><strong>Generated By:</strong> {{ auth()->user()->name ?? 'Admin User' }}</p>
            </div>
        </div>
        <hr class="print-divider">
    </div>

    <!-- Screen Title Header with Export Controls -->
    <div class="page-head-row">
        <div>
            <h1 style="font-size: 30px; margin: 0;">Reports</h1>
            <p style="margin: 2px 0 0; color: var(--ink-soft);">A clear view of your sales, stock and café performance.</p>
        </div>

        <div style="display: flex; align-items: center; gap: 8px;">
            <label style="margin: 0;">
                <select class="field field--sm" id="exportScopeSelect" style="height: 38px; padding: 6px 10px;">
                    <option value="both">Both (Sales & Inventory)</option>
                    <option value="sales">Sales Report Only</option>
                    <option value="inventory">Inventory Report Only</option>
                </select>
            </label>

            <button type="button" class="btn btn--primary btn--sm" id="btnExportReport" style="height: 38px; display: inline-flex; align-items: center; gap: 6px; white-space: nowrap;">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                Export Report
            </button>
        </div>
    </div>

    <!-- Filter Panel -->
    <x-admin.panel title="" note="">
        <div class="tab-nav-row">
            <button type="button" class="tab-btn tab-btn--active" id="btnReportSales">
                📊 Sales Report
            </button>
            <button type="button" class="tab-btn tab-btn--inactive" id="btnReportInventory">
                📦 Inventory Report
            </button>
        </div>

        <div class="filter-grid-row">
            <label class="field-group fg-branch">
                <span>Branch</span>
                <select class="field" id="reportBranch">
                    <option value="all">All branches</option>
                    @foreach($branches as $branch)
                        <option value="{{ $branch }}">{{ $branch }}</option>
                    @endforeach
                </select>
            </label>

            <label class="field-group fg-branch">
                <span>View by</span>
                <select class="field" id="reportViewBy">
                    <option value="day">A single day</option>
                    <option value="month">A month</option>
                    <option value="year">A year</option>
                </select>
            </label>

            <label class="field-group fg-branch">
                <span>Date</span>
                <input type="date" class="field" id="reportDate" value="{{ \Illuminate\Support\Carbon::today()->format('Y-m-d') }}">
            </label>

            <label class="field-group fg-branch" id="invSubTabGroup" hidden>
                <span>Report Category</span>
                <select class="field" id="selectInvCategory">
                    <option value="overview">Overview</option>
                    <option value="movements">Stock movements</option>
                    <option value="usage">Usage & waste</option>
                    <option value="value">Stock value</option>
                </select>
            </label>
        </div>
    </x-admin.panel>

    <!-- VIEW 1: SALES REPORT -->
    <div id="sectionSalesReport">
        <div class="stat-row">
            <article class="stat-card">
                <p class="stat-card-title">Gross sales</p>
                <p class="stat-card-value" id="valGrossSales">₱0.00</p>
                <p class="stat-card-sub">Estimated for selected date</p>
            </article>

            <article class="stat-card">
                <p class="stat-card-title">Orders</p>
                <p class="stat-card-value" id="valTotalOrders">0</p>
                <p class="stat-card-sub">Closed transactions</p>
            </article>

            <article class="stat-card">
                <p class="stat-card-title">Average ticket</p>
                <p class="stat-card-value" id="valAvgTicket">₱0.00</p>
                <p class="stat-card-sub">Per transaction</p>
            </article>

            <article class="stat-card">
                <p class="stat-card-title">Cups served</p>
                <p class="stat-card-value" id="valCupsServed">0</p>
                <p class="stat-card-sub">All drinks fulfilled</p>
            </article>
        </div>

        <div class="grid-2">
            <x-admin.panel title="Sales over time" note="Daily takings · recorded period">
                <div class="sales-chart-container" id="chartSalesOverTime"></div>
                <div class="chart-legend-row">
                    <span class="chart-dot dot--sales"></span> Total sales
                </div>
            </x-admin.panel>

            <x-admin.panel title="Payment breakdown" note="Payment method share">
                <div class="payment-split-wrapper" id="boxPaymentSplit"></div>
            </x-admin.panel>
        </div>

        <x-admin.panel title="Sales by branch" note="Branch revenue performance comparison">
            <ul class="branch-rank-list" id="listSalesByBranch"></ul>
        </x-admin.panel>

        <x-admin.panel title="Menu performance" note="Item sales volume and revenue contribution">
            <h3 class="sub-head">Revenue by drink</h3>
            <div class="horizontal-bars-container" id="barsMenuRevenue"></div>

            <h3 class="sub-head subhead-spaced">Drink breakdown</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Drink</th>
                        <th class="ta-r">Cups sold</th>
                        <th class="ta-r">Revenue</th>
                        <th class="ta-r">Share</th>
                    </tr>
                </thead>
                <tbody id="tableMenuBreakdown"></tbody>
            </table>

            <!-- Drink Breakdown Pagination -->
            <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 12px; padding-top: 8px; border-top: 1px solid var(--border-color, #e5e7eb);">
                <span id="menuPageInfo" style="font-size: 13px; color: #6b7280;">Showing items</span>
                <div style="display: flex; gap: 6px;">
                    <button type="button" class="btn btn--sm" id="btnMenuPrev" style="padding: 4px 10px;">&larr; Prev</button>
                    <button type="button" class="btn btn--sm" id="btnMenuNext" style="padding: 4px 10px;">Next &rarr;</button>
                </div>
            </div>
        </x-admin.panel>
    </div>

    <!-- VIEW 2: INVENTORY REPORT -->
    <div id="sectionInventoryReport" hidden>
        <div class="stat-row">
            <article class="stat-card">
                <p class="stat-card-title">Items below reorder level</p>
                <div class="stat-card-value-row">
                    <span class="stat-card-value" id="invCountReorder">0</span>
                    <span class="badge badge--low" id="badgeNeedsAttention">Needs attention</span>
                </div>
                <p class="stat-card-sub" id="invTrackedNote">Tracked raw ingredients</p>
            </article>

            <article class="stat-card">
                <p class="stat-card-title">Stock received</p>
                <p class="stat-card-value" id="valStockReceived">₱{{ number_format($invMetrics['stock_received_cost'] ?? 0, 2) }}</p>
                <p class="stat-card-sub">Restock deliveries</p>
            </article>

            <article class="stat-card">
                <p class="stat-card-title">Waste cost</p>
                <p class="stat-card-value" id="valWasteCost">₱{{ number_format($invMetrics['waste_cost'] ?? 0, 2) }}</p>
                <p class="stat-card-sub">Recorded spoilage & waste</p>
            </article>

            <article class="stat-card">
                <p class="stat-card-title">Closing stock value</p>
                <p class="stat-card-value" id="valClosingStockValue">₱{{ number_format($invMetrics['closing_stock_value'] ?? 0, 2) }}</p>
                <p class="stat-card-sub">Purchase cost valuation basis</p>
            </article>
        </div>

        <!-- Hidden by default unless low stock exists -->
        <div id="panelItemsNeedingAttention" hidden>
            <x-admin.panel title="Items needing attention" note="Ingredients at or below reorder threshold">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Ingredient</th>
                            <th class="ta-r">On hand</th>
                            <th class="ta-r">Reorder level</th>
                            <th class="ta-r">Est. days remaining</th>
                            <th class="ta-r">Status</th>
                        </tr>
                    </thead>
                    <tbody id="tableItemsNeedingAttention"></tbody>
                </table>
            </x-admin.panel>
        </div>

        <div class="grid-2">
            <x-admin.panel title="Top 8 Ingredient usage trend" note="Top 8 consumed raw ingredients today">
                <div id="boxIngredientUsageTrend">
                    <p class="empty-state-sub" style="padding: 12px; text-align: center;">Loading consumption analytics...</p>
                </div>
            </x-admin.panel>

            <x-admin.panel title="Recent stock movements" note="Log of stock movements for selected range">
                <div id="boxRecentMovements">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Ingredient</th>
                                <th>Reason</th>
                                <th class="ta-r">Change</th>
                            </tr>
                        </thead>
                        <tbody id="tableRecentMovements"></tbody>
                    </table>

                    <!-- Recent Movements Pagination -->
                    <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 12px; padding-top: 8px; border-top: 1px solid var(--border-color, #e5e7eb);">
                        <span id="movementsPageInfo" style="font-size: 13px; color: #6b7280;">Showing items</span>
                        <div style="display: flex; gap: 6px;">
                            <button type="button" class="btn btn--sm" id="btnMovementsPrev" style="padding: 4px 10px;">&larr; Prev</button>
                            <button type="button" class="btn btn--sm" id="btnMovementsNext" style="padding: 4px 10px;">Next &rarr;</button>
                        </div>
                    </div>
                </div>
            </x-admin.panel>
        </div>

        <!-- Stock Reconciliation Table -->
        <x-admin.panel title="Stock reconciliation" note="Base unit quantities per ingredient">
            <table class="table">
                <thead>
                    <tr>
                        <th>Ingredient</th>
                        <th class="ta-r">Opening stock</th>
                        <th class="ta-r">Received</th>
                        <th class="ta-r">Estimated consumption</th>
                        <th class="ta-r">Waste</th>
                        <th class="ta-r">Adjustments</th>
                        <th class="ta-r">Closing stock</th>
                    </tr>
                </thead>
                <tbody id="tableStockReconciliation"></tbody>
            </table>

            <!-- Pagination Bar -->
            <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 16px; padding-top: 12px; border-top: 1px solid var(--border-color, #e5e7eb);">
                <span id="reconcilePageInfo" style="font-size: 13px; color: #6b7280;">Showing 1 to 10 of items</span>
                <div style="display: flex; gap: 8px;">
                    <button type="button" class="btn btn--sm" id="btnReconcilePrev" style="padding: 4px 12px;">&larr; Previous</button>
                    <button type="button" class="btn btn--sm" id="btnReconcileNext" style="padding: 4px 12px;">Next &rarr;</button>
                </div>
            </div>
        </x-admin.panel>
    </div>

    @push('scripts')
        <script src="{{ asset('js/Admin.js') }}"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                window.KAPE_REPORTS = {
                    sales: @json($sales),
                    topItems: @json($topItems),
                    ingredients: @json($ingredients),
                    branches: @json($branches),
                    orders: @json($orders),
                    movements: @json($movements),
                    invMetrics: @json($invMetrics)
                };
                if (typeof initReports === 'function') {
                    initReports();
                }
            });
        </script>
    @endpush

</x-admin.shell>